-- MySQL Script generated by MySQL Workbench
-- Thu Dec  3 13:59:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema poke_baza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema poke_baza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `poke_baza` DEFAULT CHARACTER SET utf8 ;
USE `poke_baza` ;

-- -----------------------------------------------------
-- Table `poke_baza`.`Trener`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poke_baza`.`Trener` (
  `trener_id` INT(11) NOT NULL,
  `Imie` VARCHAR(45) NOT NULL,
  `Nazwisko` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`trener_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poke_baza`.`Trener_pokemony`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poke_baza`.`Trener_pokemony` (
  `idTrener_pokemony` INT NOT NULL,
  `Trener_trener_id` INT(11) NOT NULL,
  PRIMARY KEY (`idTrener_pokemony`),
  INDEX `fk_Trener_pokemony_Trener1_idx` (`Trener_trener_id` ASC),
  CONSTRAINT `fk_Trener_pokemony_Trener1`
    FOREIGN KEY (`Trener_trener_id`)
    REFERENCES `poke_baza`.`Trener` (`trener_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poke_baza`.`pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poke_baza`.`pokemon` (
  `pok_id` INT(11) NOT NULL,
  `pok_nazwa` VARCHAR(45) NOT NULL,
  `pok_waga` INT(11) NULL,
  `pok_wzrost` INT(11) NULL,
  `Trener_pokemony_idTrener_pokemony` INT NOT NULL,
  PRIMARY KEY (`pok_id`, `Trener_pokemony_idTrener_pokemony`),
  INDEX `fk_pokemon_Trener_pokemony1_idx` (`Trener_pokemony_idTrener_pokemony` ASC),
  CONSTRAINT `fk_pokemon_Trener_pokemony1`
    FOREIGN KEY (`Trener_pokemony_idTrener_pokemony`)
    REFERENCES `poke_baza`.`Trener_pokemony` (`idTrener_pokemony`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poke_baza`.`wersja_gry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poke_baza`.`wersja_gry` (
  `wersja_id` INT(11) NOT NULL,
  `wersja_nazwa` VARCHAR(45) NOT NULL,
  `pokemon_pok_id` INT(11) NOT NULL,
  PRIMARY KEY (`wersja_id`, `pokemon_pok_id`),
  INDEX `fk_wersja_gry_pokemon_idx` (`pokemon_pok_id` ASC),
  CONSTRAINT `fk_wersja_gry_pokemon`
    FOREIGN KEY (`pokemon_pok_id`)
    REFERENCES `poke_baza`.`pokemon` (`pok_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poke_baza`.`podstawowe_staty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poke_baza`.`podstawowe_staty` (
  `pod_hp` INT(11) NULL,
  `pod_atk` INT(11) NULL,
  `pod_def` INT(11) NULL,
  `pod_sp_atk` INT(11) NULL,
  `pod_sp_def` INT(11) NULL,
  `pod_speed` INT(11) NULL,
  `pokemon_pok_id` INT(11) NOT NULL,
  PRIMARY KEY (`pokemon_pok_id`),
  INDEX `fk_podstawowe_staty_pokemon1_idx` (`pokemon_pok_id` ASC),
  CONSTRAINT `fk_podstawowe_staty_pokemon1`
    FOREIGN KEY (`pokemon_pok_id`)
    REFERENCES `poke_baza`.`pokemon` (`pok_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poke_baza`.`typy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poke_baza`.`typy` (
  `typ_id` INT NOT NULL,
  `typ_nazwa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`typ_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poke_baza`.`pokemon_typy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poke_baza`.`pokemon_typy` (
  `typy_typ_id` INT NOT NULL,
  `pokemon_pok_id` INT(11) NOT NULL,
  INDEX `fk_pokemon_typy_typy1_idx` (`typy_typ_id` ASC) ,
  PRIMARY KEY (`pokemon_pok_id`),
  CONSTRAINT `fk_pokemon_typy_typy1`
    FOREIGN KEY (`typy_typ_id`)
    REFERENCES `poke_baza`.`typy` (`typ_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pokemon_typy_pokemon1`
    FOREIGN KEY (`pokemon_pok_id`)
    REFERENCES `poke_baza`.`pokemon` (`pok_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poke_baza`.`ruchy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poke_baza`.`ruchy` (
  `ruch_id` INT(11) NOT NULL,
  `ruch_nazwa` VARCHAR(45) NOT NULL,
  `typy_typ_id` INT NOT NULL,
  `ruch_sila` SMALLINT(6) NULL,
  `ruch_koszt` SMALLINT(6) NULL,
  `ruch_celnosc` SMALLINT(6) NULL,
  PRIMARY KEY (`ruch_id`),
  INDEX `fk_ruchy_typy1_idx` (`typy_typ_id` ASC) ,
  CONSTRAINT `fk_ruchy_typy1`
    FOREIGN KEY (`typy_typ_id`)
    REFERENCES `poke_baza`.`typy` (`typ_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poke_baza`.`pokemon_ruchy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poke_baza`.`pokemon_ruchy` (
  `idpokemon_ruchy` INT NOT NULL,
  `pokemon_pok_id` INT(11) NOT NULL,
  `ruchy_ruch_id` INT(11) NOT NULL,
  PRIMARY KEY (`idpokemon_ruchy`, `pokemon_pok_id`, `ruchy_ruch_id`),
  INDEX `fk_pokemon_ruchy_pokemon1_idx` (`pokemon_pok_id` ASC) ,
  INDEX `fk_pokemon_ruchy_ruchy1_idx` (`ruchy_ruch_id` ASC) ,
  CONSTRAINT `fk_pokemon_ruchy_pokemon1`
    FOREIGN KEY (`pokemon_pok_id`)
    REFERENCES `poke_baza`.`pokemon` (`pok_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pokemon_ruchy_ruchy1`
    FOREIGN KEY (`ruchy_ruch_id`)
    REFERENCES `poke_baza`.`ruchy` (`ruch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
