# Generated by Django 3.1.4 on 2021-01-14 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pokemon',
            fields=[
                ('pok_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pok_nazwa', models.CharField(max_length=45)),
                ('pok_waga', models.IntegerField()),
                ('pok_wzrost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='trener',
            fields=[
                ('trener_id', models.IntegerField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='typy',
            fields=[
                ('typ_id', models.IntegerField(primary_key=True, serialize=False)),
                ('typ_nazwa', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='podstawowe_staty',
            fields=[
                ('pod_hp', models.IntegerField()),
                ('pod_atk', models.IntegerField()),
                ('pod_def', models.IntegerField()),
                ('pod_sp_atk', models.IntegerField()),
                ('pod_sp_def', models.IntegerField()),
                ('pod_speed', models.IntegerField()),
                ('pokemon_pok_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pokedex.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='wersja_gry',
            fields=[
                ('wersja_id', models.IntegerField(primary_key=True, serialize=False)),
                ('wersja_nazwa', models.CharField(max_length=45)),
                ('pokemon_pok_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='ruchy',
            fields=[
                ('ruch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ruch_nazwa', models.CharField(max_length=45)),
                ('ruch_sila', models.SmallIntegerField()),
                ('ruch_koszt', models.SmallIntegerField()),
                ('ruch_celnosc', models.SmallIntegerField()),
                ('typy_typ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.typy')),
            ],
        ),
        migrations.CreateModel(
            name='pokemon_typy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_pok_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokemon')),
                ('typy_typ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.typy')),
            ],
        ),
        migrations.CreateModel(
            name='pokemon_ruchy',
            fields=[
                ('idpokemon_ruchy', models.IntegerField(primary_key=True, serialize=False)),
                ('pokemon_pok_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokemon')),
                ('ruchy_ruch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.ruchy')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='trener_trener_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.trener'),
        ),
    ]
