# Generated by Django 3.1.3 on 2020-11-28 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('trener_id', models.IntegerField(primary_key=True, serialize=False)),
                ('imie', models.CharField(db_column='Imie', max_length=45)),
                ('nazwisko', models.CharField(db_column='Nazwisko', max_length=45)),
            ],
            options={
                'db_table': 'trener',
            },
        ),
        migrations.CreateModel(
            name='Typy',
            fields=[
                ('typ_id', models.IntegerField(primary_key=True, serialize=False)),
                ('typ_nazwa', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'typy',
            },
        ),
        migrations.CreateModel(
            name='Umiejetnosci',
            fields=[
                ('umi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('umi_nazwa', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'umiejetnosci',
            },
        ),
        migrations.CreateModel(
            name='PodstawoweStaty',
            fields=[
                ('pod_hp', models.IntegerField(blank=True, null=True)),
                ('pod_atk', models.IntegerField(blank=True, null=True)),
                ('pod_def', models.IntegerField(blank=True, null=True)),
                ('pod_sp_atk', models.IntegerField(blank=True, null=True)),
                ('pod_sp_def', models.IntegerField(blank=True, null=True)),
                ('pod_speed', models.IntegerField(blank=True, null=True)),
                ('pokemon_pok', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Pokedex.pokemon')),
            ],
            options={
                'db_table': 'podstawowe_staty',
            },
        ),
        migrations.CreateModel(
            name='TrenerPokemony',
            fields=[
                ('idtrener_pokemony', models.IntegerField(db_column='idTrener_pokemony', primary_key=True, serialize=False)),
                ('trener_trener', models.ForeignKey(db_column='Trener_trener_id', on_delete=django.db.models.deletion.DO_NOTHING, to='Pokedex.trener')),
            ],
            options={
                'db_table': 'trener_pokemony',
            },
        ),
        migrations.CreateModel(
            name='Ruchy',
            fields=[
                ('ruch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ruch_nazwa', models.CharField(max_length=45)),
                ('ruch_sila', models.SmallIntegerField(blank=True, null=True)),
                ('ruch_koszt', models.SmallIntegerField(blank=True, null=True)),
                ('ruch_celnosc', models.SmallIntegerField(blank=True, null=True)),
                ('typy_typ', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pokedex.typy')),
            ],
            options={
                'db_table': 'ruchy',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('pok_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pok_nazwa', models.CharField(max_length=45)),
                ('pok_waga', models.IntegerField(blank=True, null=True)),
                ('pok_wzrost', models.IntegerField(blank=True, null=True)),
                ('trener_pokemony_idtrener_pokemony', models.ForeignKey(db_column='Trener_pokemony_idTrener_pokemony', on_delete=django.db.models.deletion.DO_NOTHING, to='Pokedex.trenerpokemony')),
            ],
            options={
                'db_table': 'pokemon',
                'unique_together': {('pok_id', 'trener_pokemony_idtrener_pokemony')},
            },
        ),
        migrations.CreateModel(
            name='WersjaGry',
            fields=[
                ('wersja_id', models.IntegerField(primary_key=True, serialize=False)),
                ('wersja_nazwa', models.CharField(max_length=45)),
                ('pokemon_pok', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pokedex.pokemon')),
            ],
            options={
                'db_table': 'wersja_gry',
                'unique_together': {('wersja_id', 'pokemon_pok')},
            },
        ),
        migrations.CreateModel(
            name='PokemonUmiejetnosci',
            fields=[
                ('pokemon_pok', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Pokedex.pokemon')),
                ('umiejetnosci_umi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pokedex.umiejetnosci')),
            ],
            options={
                'db_table': 'pokemon_umiejetnosci',
            },
        ),
        migrations.CreateModel(
            name='PokemonTypy',
            fields=[
                ('pokemon_pok', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Pokedex.pokemon')),
                ('typy_typ', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pokedex.typy')),
            ],
            options={
                'db_table': 'pokemon_typy',
            },
        ),
        migrations.CreateModel(
            name='PokemonRuchy',
            fields=[
                ('idpokemon_ruchy', models.IntegerField(primary_key=True, serialize=False)),
                ('pokemon_pok', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pokedex.pokemon')),
                ('ruchy_ruch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pokedex.ruchy')),
            ],
            options={
                'db_table': 'pokemon_ruchy',
                'unique_together': {('idpokemon_ruchy', 'pokemon_pok', 'ruchy_ruch')},
            },
        ),
    ]
